.travis.yml, doc/changes/changes_0.1.0.md, doc/design.md, doc/system_requirements.md, pom.xml
=> #2 Added requirements and design

doc/changes/changes_0.2.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/ProjectFilesValidator.java, src/test/java/com/exasol/projectkeeper/ProjectFilesValidatorTest.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/resources/test_project/pom.xml
=> #10 Did not abort on unequal files

doc/changes/changes_0.2.0.md, src/main/java/com/exasol/projectkeeper/ProjectKeeperModule.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperVerifyMojo.java, src/main/java/com/exasol/projectkeeper/files/AbstractProjectFilesWalker.java, src/main/java/com/exasol/projectkeeper/files/ProjectFilesFixer.java, src/main/java/com/exasol/projectkeeper/files/ProjectFilesValidator.java, src/main/java/com/exasol/projectkeeper/pom/PomFileIO.java, src/main/java/com/exasol/projectkeeper/pom/plugin/AbstractPluginPomValidator.java, src/main/java/com/exasol/xpath/XPathErrorHanlingWrapper.java, src/test/java/com/exasol/projectkeeper/AbstractProjectKeeperMojoTest.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/files/ProjectFilesFixerTest.java, src/test/java/com/exasol/projectkeeper/files/ProjectFilesValidatorTest.java, src/test/java/com/exasol/projectkeeper/pom/PomFileValidationRunnerTest.java, src/test/java/com/exasol/projectkeeper/pom/plugin/VersionMavenPluginPomValidatorTest.java
=> #16 Added unified error codes

doc/changes/changes_0.3.0.md, src/main/java/com/exasol/projectkeeper/validators/ChangelogValidator.java, src/test/java/com/exasol/projectkeeper/validators/ChangelogValidatorTest.java
=> #26: Don't require -SNAPSHOT changes files

README.md, doc/changes/changes_0.4.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java, src/main/java/com/exasol/projectkeeper/ExcludedFilesMatcher.java, src/main/java/com/exasol/projectkeeper/validators/DeletedFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java, src/test/java/com/exasol/projectkeeper/ExcludedFilesMatcherTest.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/validators/DeletedFilesValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidatorTest.java, src/test/resources/test_project/pom.xml
=> #19: Added a configurable list for excluding files from validation

README.md, doc/changes/changes_0.4.0.md, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/dependencies/JacocoAgentDependencyValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/DependencyPluginValidator.java, src/main/resources/maven_templates/maven-dependency-plugin.xml, src/test/java/com/exasol/projectkeeper/HasValidationFindingWithMessageMatcher.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/validators/pom/PomTesting.java, src/test/java/com/exasol/projectkeeper/validators/pom/dependencies/AbstractDependencyValidatorAbstractTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/dependencies/AbstractDependencyValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/dependencies/JacocoAgentDependencyValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/AbstractMavenPluginPomValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/DependencyPluginValidatorTest.java
=> Feature/41 UDF coverage module (part 2)

doc/changes/changelog.md, doc/changes/changes_0.4.2.md, pom.xml, src/main/resources/templates/default/require_exact/src/test/resources/logging.properties, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/resources/logging.properties, src/test/resources/test_project/pom.xml
=> Added missing `.level` suffix in `logging.properties`

doc/changes/changelog.md, doc/changes/changes_0.5.0.md, pom.xml, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/resources/test_project/pom.xml
=> #55: Fixed CVE-2020-8908 by excluding guava dependency

doc/changes/changes_0.5.0.md, src/main/java/com/exasol/projectkeeper/validators/ChangelogValidator.java, src/test/java/com/exasol/projectkeeper/validators/ChangelogValidatorTest.java
=> #52: Changed behavior to not force user to create a changes file if version contains a snapshot tag

.github/workflows/maven_central_release.yml, doc/changes/changes_0.5.0.md, src/main/resources/templates/maven_central/require_exact/.github/workflows/maven_central_release.yml
=> * #61: Updated the template for Maven Central release workflow.

.github/workflows/maven_central_release.yml, doc/changes/changes_0.5.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/ProjectKeeperModule.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperVerifyMojo.java, src/main/java/com/exasol/projectkeeper/validators/ChangelogValidator.java, src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/AbstractPomValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileIO.java, src/main/java/com/exasol/projectkeeper/validators/pom/dependencies/AbstractDependencyValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/AbstractPluginPomValidator.java, src/main/java/com/exasol/xpath/XPathErrorHandlingWrapper.java, src/main/resources/templates/maven_central/require_exact/.github/workflows/maven_central_release.yml, src/test/java/com/exasol/projectkeeper/AbstractProjectKeeperMojoTest.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/validators/ChangelogValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/PomFileIOTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/PomTesting.java, src/test/java/com/exasol/projectkeeper/validators/pom/dependencies/JacocoAgentDependencyValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/AbstractMavenPluginPomValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/JacocoPluginPomValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/VersionMavenPluginPomValidatorTest.java
=> Refactored to use error message builder

doc/changes/changes_0.5.0.md, pom.xml, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java
=> #46: Refactored integration tests

README.md, doc/changes/changes_0.5.0.md, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/ErrorCodeCrawlerPluginValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/JavadocPluginValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/SourcePluginValidator.java, src/main/resources/maven_templates/error-code-crawler-maven-plugin.xml, src/main/resources/maven_templates/maven-javadoc-plugin.xml, src/main/resources/maven_templates/maven-source-plugin.xml, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/ErrorCodeCrawlerPluginValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/JavadocPluginValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/SourcePluginValidatorTest.java
=> Added_maven_plugins

doc/changes/changes_0.5.0.md, src/main/java/com/exasol/projectkeeper/validators/ChangelogValidator.java
=> bug/70: Fixed changes template

.github/workflows/broken_links_checker.yml, doc/changes/changelog.md, doc/changes/changes_0.5.0.md, doc/changes/changes_0.6.0.md, pom.xml, src/main/resources/templates/default/require_exact/.github/workflows/broken_links_checker.yml, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/resources/test_project/pom.xml
=> #67: Added broken links checker workflow

doc/changes/changes_0.6.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperFixMojo.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperVerifyMojo.java, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileIO.java, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java
=> #74: Fixed a bug that the project was only valid after running fix twice

doc/changes/changes_0.6.0.md, src/main/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeRenderer.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeRendererTest.java
=> #83: Fixed wrong format for updated dependencies

.github/workflows/broken_links_checker.yml, doc/changes/changes_0.6.0.md, src/main/resources/templates/default/require_exact/.github/workflows/broken_links_checker.yml
=> #91: Update version of links' checker workflow

doc/changes/changes_0.6.0.md, src/main/java/com/exasol/projectkeeper/validators/changesfile/DependencySectionFixer.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/LastReleasePomFileReader.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/validators/changesfile/LastReleasePomFileReaderTest.java
=> #87: Fixed failing dependency section validation after release

doc/changes/changes_0.6.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/ReproducibleBuildPluginValidator.java, src/main/resources/maven_templates/reproducible-build-maven-plugin.xml, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/ReproducibleBuildPluginValidatorTest.java
=> #93: Added validation for reproducible-build-maven-plugin

.github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/release_droid_print_quick_checksum.yml, .github/workflows/release_droid_release_on_maven_central.yml, .github/workflows/release_droid_upload_github_release_assets.yml, doc/changes/changelog.md, doc/changes/changes_0.6.1.md, pom.xml, src/main/resources/templates/default/require_exact/.github/workflows/release_droid_prepare_original_checksum.yml, src/main/resources/templates/default/require_exact/.github/workflows/release_droid_print_quick_checksum.yml, src/main/resources/templates/default/require_exact/.github/workflows/release_droid_upload_github_release_assets.yml, src/main/resources/templates/maven_central/require_exact/.github/workflows/release_droid_release_on_maven_central.yml, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/resources/test_project/pom.xml
=> #102: Fixed bug that blocked releasing

README.md, dependencies.md, doc/changes/changes_0.7.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java, src/main/java/com/exasol/projectkeeper/BrokenLinkReplacer.java, src/main/java/com/exasol/projectkeeper/validators/dependencies/DependenciesBrokenLinkReplacer.java, src/main/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidator.java, src/test/java/com/exasol/projectkeeper/BrokenLinkReplacerTest.java, src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesBrokenLinkReplacerTest.java, src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidatorIT.java
=> #99: Added replacement of broken urls

doc/changes/changes_0.7.0.md, src/main/java/com/exasol/projectkeeper/ProjectKeeperVerifyMojo.java, src/main/java/com/exasol/projectkeeper/validators/DeletedFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/DependencySectionFixer.java, src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/AbstractPluginPomValidator.java
=> #106: Fixed sonar security hotspots

doc/changes/changes_0.8.0.md, src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperFixMojo.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperVerifyMojo.java, src/main/java/com/exasol/projectkeeper/pom/DefaultMavenArtifactModelReader.java, src/main/java/com/exasol/projectkeeper/repository/GitRepository.java, src/main/java/com/exasol/projectkeeper/validators/DeletedFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileIO.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/DependencySectionFixer.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/LastReleasePomFileReader.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeRenderer.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportReader.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRenderer.java, src/main/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidator.java, src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java, src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRenderer.java, src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/MarkdownReferenceBuilder.java, src/main/java/com/exasol/projectkeeper/validators/files/InputStreamComparator.java, src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/AbstractPomValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileIO.java, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/dependencies/AbstractDependencyValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/dependencies/JacocoAgentDependencyValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/AbstractPluginPomValidator.java, src/main/java/com/exasol/xpath/XPathSplitter.java
=> refactor/110: Replaced explicit types by var

dependencies.md, doc/changes/changes_0.8.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/JacocoPluginPomValidator.java, src/main/java/com/exasol/xpath/XPathErrorHandlingWrapper.java, src/main/resources/maven_templates/jacoco-maven-plugin.xml, src/test/java/com/exasol/projectkeeper/ProjectKeeperAbstractIT.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/JacocoPluginPomValidatorTest.java
=> refactor/111: Extract coverage from integration tests

doc/changes/changes_0.8.0.md, src/main/java/com/exasol/projectkeeper/ProjectKeeperFixMojo.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperVerifyMojo.java, src/main/java/com/exasol/projectkeeper/Validator.java, src/main/java/com/exasol/projectkeeper/validators/DeletedFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidator.java, src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, src/test/java/com/exasol/projectkeeper/AbstractValidationMatcher.java, src/test/java/com/exasol/projectkeeper/HasNoMoreFindingsAfterApplyingFixesMatcher.java, src/test/java/com/exasol/projectkeeper/HasValidationFindingWithMessageMatcher.java, src/test/java/com/exasol/projectkeeper/validators/DeletedFilesValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/MavenDependencyComparatorTest.java, src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidatorIT.java, src/test/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/PomTesting.java, src/test/java/com/exasol/projectkeeper/validators/pom/dependencies/AbstractDependencyValidatorAbstractTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/dependencies/AbstractDependencyValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/pom/dependencies/JacocoAgentDependencyValidatorTest.java
=> feature/80: Made validation API functional

doc/changes/changes_0.8.0.md, src/main/java/com/exasol/projectkeeper/ValidationFinding.java, src/main/java/com/exasol/projectkeeper/validators/DeletedFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidator.java, src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/dependencies/AbstractDependencyValidator.java, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/AbstractPluginPomValidator.java, src/test/java/com/exasol/projectkeeper/ValidationFindingTest.java
=> #79: Added builder for ValidationFinding

dependencies.md, doc/changes/changes_0.7.1.md, doc/changes/changes_0.8.0.md, pom.xml, src/test/java/com/exasol/projectkeeper/ProjectKeeperAbstractIT.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java
=> #114: Extracted library for maven plugin testing

doc/changes/changes_0.7.1.md, src/main/java/com/exasol/projectkeeper/validators/changesfile/DependencySectionFixer.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/TemporaryPomFile.java, src/test/java/com/exasol/projectkeeper/validators/changesfile/TemporaryPomFileTest.java
=> #125: Fixed sonar findings

doc/changes/changelog.md, doc/changes/changes_0.7.3.md, pom.xml, src/main/java/com/exasol/projectkeeper/pom/MavenModelFromRepositoryReader.java
=> #138: Fixed dependency crawling for dependencies with unreachable dependencies

doc/changes/changes_0.7.3.md, src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java
=> #134: Fixed missing code name in changes_x.x.x.md template

doc/changes/changes_0.8.0.md, src/main/java/com/exasol/projectkeeper/BrokenLinkReplacer.java, src/test/java/com/exasol/projectkeeper/BrokenLinkReplacerTest.java
=> #144 Fixed that whitespace in linkReplacement was not stripped

doc/changes/changes_0.8.0.md, src/main/java/com/exasol/projectkeeper/validators/pom/plugin/JavadocPluginValidator.java, src/test/java/com/exasol/projectkeeper/validators/pom/plugin/JavadocPluginValidatorTest.java
=> #108: Allowed configuration on javadoc plugin

.github/workflows/ci-build.yml, README.md, doc/changes/changes_0.9.0.md, doc/design.md, doc/system_requirements.md, src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperFixMojo.java, src/main/java/com/exasol/projectkeeper/repository/GitRepository.java, src/main/java/com/exasol/projectkeeper/validators/AbstractFileContentValidator.java, src/main/java/com/exasol/projectkeeper/validators/AbstractFileStringValidator.java, src/main/java/com/exasol/projectkeeper/validators/AbstractFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/ReadmeValidator.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/repository/GitRepositoryTest.java, src/test/java/com/exasol/projectkeeper/validators/ReadmeValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidatorTest.java
=> feature/96: Added validation of README.md

.github/workflows/broken_links_checker.yml, README.md, doc/changes/changelog.md, doc/changes/changes_0.10.0.md, mlc_config.json, pom.xml, src/main/resources/templates/default/require_exact/.github/workflows/broken_links_checker.yml
=> bug/154: Replaced broken-link-checker

.github/workflows/broken_links_checker.yml, .github/workflows/release_droid_upload_github_release_assets.yml, doc/changes/changes_0.10.0.md, pom.xml, src/main/resources/templates/default/require_exact/.github/workflows/release_droid_upload_github_release_assets.yml
=> feature/156: Change GitHub release action to upload error-code-report

.github/workflows/ci-build.yml, doc/changes/changes_0.10.0.md, src/main/resources/templates/default/require_exist/.github/workflows/ci-build.yml
=> feature/158: Improved CI build template

doc/changes/changelog.md, doc/changes/changes_0.11.0.md, doc/design.md, doc/system_requirements.md, pom.xml, src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java, src/main/java/com/exasol/projectkeeper/validators/LicenseFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/ReadmeFileValidator.java, src/main/resources/LICENSE-template, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/validators/LicenseFileValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/ReadmeFileValidatorTest.java
=> feature/69: Made year in license variable

.github/workflows/release_droid_upload_github_release_assets.yml, doc/changes/changes_0.11.0.md, src/main/resources/templates/default/require_exact/.github/workflows/release_droid_upload_github_release_assets.yml
Update for release_droid_upload_github_release_assets.yml file
Closes #166
=> feature/166: Update for github release action

doc/changes/changelog.md, doc/changes/changes_1.0.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java, src/main/java/com/exasol/projectkeeper/validators/AbstractFileContentValidator.java, src/main/java/com/exasol/projectkeeper/validators/AbstractFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/LicenseFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/ReadmeFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/changelog/ChangelogFileValidator.java, src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java, src/test/java/com/exasol/projectkeeper/validators/LicenseFileValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/ReadmeFileValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/changelog/ChangelogFileValidatorTest.java, src/test/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidatorTest.java
=> bug/170: Fixed excludedFiles for README.md validation

README.md, doc/changes/changelog.md, doc/changes/changes_1.2.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperFixMojo.java, src/main/java/com/exasol/projectkeeper/ProjectKeeperVerifyMojo.java, src/test/java/com/exasol/projectkeeper/AbstractProjectKeeperMojoTest.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java
=> feature/176: Added skip property

dependencies.md, doc/changes/changes_1.2.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/validators/pom/dependencies/JacocoAgentDependencyValidator.java, src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java
=> feature/178: Moved jacoco dependency to test scope

.github/workflows/test_linux_build_on_windows.yml, doc/changes/changelog.md, doc/changes/changes_1.3.0.md, pom.xml, src/main/java/com/exasol/projectkeeper/validators/pom/properties/PomPropertyValidator.java, src/test/java/com/exasol/projectkeeper/validators/pom/properties/PomPropertyValidatorTest.java
=> bug/174: Fixed verification for properties in pom with whitespace

.github/workflows/ci-build-next-java.yml, README.md, doc/changes/changes_1.3.2.md, src/main/resources/templates/default/require_exact/.github/workflows/ci-build-next-java.yml
+ doc/168: Added troubleshooting section
Closes #168
Closes #193
=> bug/193: Renamed next-java github-actions job

doc/changes/changes_1.3.3.md, src/main/resources/templates/default/require_exist/.github/workflows/ci-build.yml
=> #191: Add caching for sonar packages

.github/workflows/broken_links_checker.json, .github/workflows/broken_links_checker.yml, doc/changes/changes_1.3.3.md, src/main/resources/templates/default/require_exact/.github/workflows/broken_links_checker.json, src/main/resources/templates/default/require_exact/.github/workflows/broken_links_checker.yml, src/main/resources/templates/default/require_exist/doc/changes/changelog.md
=> #175: Update broken links checker to accept status 429

.github/workflows/broken_links_checker.json, .github/workflows/broken_links_checker.yml, doc/changes/changelog.md, doc/changes/changes_1.3.4.md, pom.xml, src/main/resources/templates/default/require_exact/.github/workflows/broken_links_checker.json, src/main/resources/templates/default/require_exact/.github/workflows/broken_links_checker.yml
=> #205: Replace links checker config file

.github/workflows/broken_links_checker.yml, .github/workflows/ci-build-next-java.yml, .github/workflows/ci-build.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, doc/changes/changes_1.3.4.md, pom.xml, src/main/resources/templates/default/require_exact/.github/workflows/broken_links_checker.yml, src/main/resources/templates/default/require_exact/.github/workflows/ci-build-next-java.yml, src/main/resources/templates/default/require_exist/.github/workflows/ci-build.yml
=> #207: Push trigger only build on main branch

doc/changes/changes_2.0.0.md, project-keeper/src/main/java/com/exasol/projectkeeper/ApStyleFormatter.java, project-keeper/src/main/java/com/exasol/projectkeeper/ProjectKeeper.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/changesfile/DependencySectionFixer.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/changesfile/NamedDependencyChangeReport.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRenderer.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRenderer.java, project-keeper/src/test/java/com/exasol/projectkeeper/ApStyleFormatterTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidatorIT.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/DependencySectionFixerIT.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRendererTest.java
=> refactor/235: Refactored ChangesFileValidator to support maven multi-module projects

doc/changes/changelog.md, doc/changes/changes_2.2.0.md, maven-project-crawler/pk_generated_parent.pom, parent-pom/pom.xml, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/src/main/resources/maven_templates/artifact-reference-checker-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/error-code-crawler-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-failsafe-plugin.xml, project-keeper/src/main/resources/maven_templates/ossindex-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/versions-maven-plugin.xml, shared-model-classes/pk_generated_parent.pom
=> feature/259: Added ids to maven plugin executions

.github/workflows/broken_links_checker.yml, .github/workflows/ci-build-next-java.yml, .github/workflows/ci-build.yml, .github/workflows/dependencies_check.yml, .github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/release_droid_print_quick_checksum.yml, .github/workflows/release_droid_release_on_maven_central.yml, .github/workflows/release_droid_upload_github_release_assets.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, README.md, dependencies.md, doc/changes/changes_2.2.0.md, maven-project-crawler/pom.xml, parent-pom/pom.xml, project-keeper-maven-plugin/pom.xml, project-keeper/pom.xml, project-keeper/src/main/resources/templates/.github/workflows/broken_links_checker.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build-next-java.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml, project-keeper/src/main/resources/templates/.github/workflows/dependencies_check.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_prepare_original_checksum.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_print_quick_checksum.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_release_on_maven_central.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_upload_github_release_assets.yml
=> refactor/246: Renamed repository to project-keeper

.github/workflows/broken_links_checker.yml, .github/workflows/ci-build-next-java.yml, .github/workflows/ci-build.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, doc/changes/changes_2.2.0.md, project-keeper/src/main/resources/templates/.github/workflows/broken_links_checker.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build-next-java.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml
=> feature/242: Added cancelling of GitHub action in-progress

doc/changes/changelog.md, doc/changes/changes_2.3.0.md, parent-pom/pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java
262: Added automatic fix for the version of parent pom reference in the pom.xml
Closes #262
=> feature/262: Added automatic fix for the version of parent pom 

.github/workflows/ci-build.yml, dependencies.md, doc/changes/changes_2.3.0.md, maven-project-crawler/pk_generated_parent.pom, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileGenerator.java, project-keeper/src/main/resources/maven_templates/sonar-maven-plugin.xml, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml, project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileGeneratorTest.java, shared-model-classes/pk_generated_parent.pom
... to make maven in the CI pick the one from the correct org.
Closes #216
=> refactor/216: Added sonar-plugin to pk_generated_parent.pom 

README.md, dependencies.md, doc/changes/changes_2.3.0.md, maven-project-crawler/src/test/java/com/exasol/projectkeeper/TestMavenModel.java, parent-pom/pom.xml, project-keeper/error_code_config.yml, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/FileTemplatesFactory.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/RequiredFileValidator.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, project-keeper/src/main/resources/templates/release_config.yml, project-keeper/src/test/java/com/exasol/projectkeeper/validators/TestMavenModel.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidatorTest.java, release_config.yml
=> Feature/#130 Validate release-droid config

doc/changes/changes_2.3.0.md, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_prepare_original_checksum.yml
=> #198: Enable testcontainer reuse

.github/workflows/broken_links_checker.yml, .github/workflows/ci-build-next-java.yml, .github/workflows/ci-build.yml, .github/workflows/dependencies_check.yml, .github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/release_droid_print_quick_checksum.yml, .github/workflows/release_droid_release_on_maven_central.yml, .github/workflows/release_droid_upload_github_release_assets.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, README.md, doc/changes/changes_2.3.1.md, parent-pom/pom.xml, project-keeper/src/main/resources/templates/.github/workflows/broken_links_checker.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build-native-build.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build-next-java.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml, project-keeper/src/main/resources/templates/.github/workflows/dependencies_check.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_prepare_original_checksum.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_print_quick_checksum.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_release_on_maven_central.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_upload_github_release_assets.yml
=> Pin version of link checker

doc/changes/changes_2.4.2.md, maven-project-crawler/pk_generated_parent.pom, project-keeper-cli/pk_generated_parent.pom, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/src/main/resources/maven_templates/jacoco-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-assembly-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-compiler-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-dependency-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-jar-plugin-exclusion.xml, project-keeper/src/main/resources/maven_templates/maven-javadoc-plugin.xml, project-keeper/src/main/resources/maven_templates/nexus-staging-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/ossindex-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/versions-maven-plugin.xml, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom
=> #301: Updated maven plugin template versions

.github/workflows/broken_links_checker.yml, .project-keeper.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_2.4.4.md, parent-pom/pom.xml, project-keeper/src/main/resources/templates/.github/workflows/broken_links_checker.yml
=> #308: Ignore URLs to opensource.org in broken link checker

doc/changes/changes_2.4.4.md, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzer.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzerTest.java
=> bug/307: Fixed unreadable error when specifying go dir instead of go.mod

dependencies.md, doc/changes/changelog.md, doc/changes/changes_2.4.5.md, maven-project-crawler/pom.xml, parent-pom/pom.xml, pom.xml, project-keeper-cli/pom.xml, project-keeper-cli/src/test/java/com/exasol/projectkeeper/cli/ProjectKeeperLauncherExecutableJarIT.java, project-keeper-maven-plugin/pom.xml, project-keeper/error_code_config.yml, project-keeper/pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoProcess.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangDependencyCalculator.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangServices.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzer.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/SimpleProcess.java, project-keeper/src/test/java/com/exasol/projectkeeper/ProjectKeeperGolangIT.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangDependencyCalculatorTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzerIT.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzerTest.java, shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/dependencies/ProjectDependency.java, shared-model-classes/src/test/java/com/exasol/projectkeeper/shared/dependencies/ProjectDependencyTest.java, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/GolangProjectFixture.java
=> #279: Fix getting licenses for Go test dependencies

.project-keeper.yml, doc/changes/changes_2.4.5.md, project-keeper/src/main/java/com/exasol/projectkeeper/BrokenLinkReplacer.java
=> #316: Add new default link replacements

.github/workflows/ci-build.yml, .github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_2.5.0.md, doc/developers_guide/developers_guide.md, parent-pom/pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangServices.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRenderer.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/MarkdownReferenceBuilder.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/dependencies/renderer/MarkdownReferenceBuilderTest.java, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/GolangProjectFixture.java
=> bug/322: Fixed unstable link order in dependencies.md

.github/workflows/dependencies_check.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_2.5.1.md, maven-project-crawler/pk_generated_parent.pom, parent-pom/pom.xml, pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-cli/pom.xml, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/pom.xml, project-keeper/src/main/resources/maven_templates/error-code-crawler-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-enforcer-plugin.xml, release.sh, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom
=> #330: Fix dependency check

dependencies.md, doc/changes/changes_2.5.1.md, maven-project-crawler/pk_generated_parent.pom, project-keeper-cli/pk_generated_parent.pom, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileGenerator.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileGeneratorTest.java, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom
=> #132: Ensure that reproducible build plugin is the last one

doc/changes/changes_2.5.1.md, project-keeper/error_code_config.yml, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangDependencyCalculator.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangDependencyChangeCalculator.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangServices.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/OwnVersionValidator.java, project-keeper/src/test/java/com/exasol/projectkeeper/ProjectKeeperGolangIT.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangDependencyCalculatorTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangDependencyChangeCalculatorTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzerIT.java, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/GolangProjectFixture.java
=> #331 Fix retrieving golang dependencies

doc/changes/changes_2.5.1.md, project-keeper/src/main/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRenderer.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRendererTest.java
=> #162: Omit empty dependency update section from changelog

README.md, doc/changes/changelog.md, doc/changes/changes_2.7.0.md, doc/developers_guide/developers_guide.md, parent-pom/pom.xml, pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/validators/finding/FindingFilter.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/finding/FindingFilterTest.java
=> #354 rexexp multiline by default

doc/changes/changes_2.7.0.md, project-keeper/src/main/resources/templates/.github/workflows/release_droid_upload_github_release_assets.yml
=> Fixed #340 Compute sha256sum inside the target directory

doc/changes/changes_2.7.0.md, doc/developers_guide/developers_guide.md, maven-project-crawler/src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java, project-keeper/src/main/java/com/exasol/projectkeeper/ProjectKeeper.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/FileTemplatesFactory.java
additionally enhanced documentation
fixes #350
=> #350 Changed PK to skip copying templates

README.md, doc/changes/changelog.md, doc/changes/changes_2.7.1.md, doc/developers_guide/developers_guide.md, parent-pom/pom.xml, pom.xml, project-keeper-cli/pom.xml, project-keeper-maven-plugin/pom.xml, project-keeper/pom.xml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_upload_github_release_assets.yml, shared-test-setup/pom.xml
=> #371 implemented

doc/changes/changes_2.9.0.md, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java
=> #388: Added path of POM file to warning message W-PK-CORE-151.

doc/changes/changes_2.9.0.md, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangDependencyType.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangDependencyChangeCalculatorTest.java, shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/dependencies/BaseDependency.java
=> #390: Reporting removed Go dependencies as type "unknown".

doc/changes/changelog.md, doc/changes/changes_2.9.2.md, error_code_config.yml, parent-pom/pom.xml, pom.xml, project-keeper-cli/pom.xml, project-keeper-maven-plugin/pom.xml, project-keeper/pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/npm/NpmServices.java, project-keeper/src/main/resources/non_maven_templates/.github/workflows/project-keeper-verify.yml, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/npm/NpmServicesTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidatorIT.java, release_config.yml, shared-test-setup/pom.xml
=> #403: Added `npm ci` before checking npm licenses

dependencies.md, doc/changes/changes_2.9.2.md, parent-pom/pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoModFileParser.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GoModFileTest.java, project-keeper/src/test/resources/go.mod
=> #411: Ignore unknown entries in go.mod

.github/workflows/ci-build.yml, .github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_2.9.3.md, maven-project-crawler/pom.xml, parent-pom/pom.xml, pom.xml, project-keeper-cli/pom.xml, project-keeper-maven-plugin/pom.xml, project-keeper/pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoBinary.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangServices.java, project-keeper/src/main/resources/non_maven_templates/.github/workflows/project-keeper-verify.yml, shared-model-classes/pom.xml
=> #421: Fix workflow script

doc/changes/changes_2.9.3.md, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/generic/CommandExecutor.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangServices.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/SimpleProcess.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/npm/NpmServices.java, project-keeper/src/main/resources/non_maven_templates/.github/workflows/project-keeper.sh, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/npm/NpmServicesTest.java
=> #422 Fix fetching npm dependencies

.project-keeper.yml, dependencies.md, doc/changes/changes_2.9.4.md, maven-project-crawler/pk_generated_parent.pom, maven-project-crawler/pom.xml, parent-pom/pom.xml, pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-cli/pom.xml, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper-maven-plugin/pom.xml, project-keeper/pk_generated_parent.pom, project-keeper/pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/config/ProjectKeeperConfigReader.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileGenerator.java, project-keeper/src/main/resources/maven_templates/maven-assembly-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-deploy-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-enforcer-plugin.xml, project-keeper/src/test/java/com/exasol/projectkeeper/config/ProjectKeeperConfigReaderTest.java, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom, shared-test-setup/pom.xml, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/ProjectKeeperConfigWriter.java
=> #430: upgrade dependencies

doc/changes/changes_2.9.4.md, project-keeper-cli/pk_generated_parent.pom, project-keeper-cli/pom.xml, project-keeper/src/main/resources/maven_templates/maven-assembly-plugin.xml, project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java
=> #427: Add implementation entries to Manifest generated by maven-assembly-plugin

README.md, doc/changes/changes_2.9.4.md, project-keeper/src/main/java/com/exasol/projectkeeper/validators/ReadmeFileValidator.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/ReadmeFileValidatorTest.java
=> #359: Use `-` instead of emdash in Maven Central badge label

.github/workflows/broken_links_checker.yml, doc/changes/changes_2.9.8.md, project-keeper/src/main/resources/templates/.github/workflows/broken_links_checker.yml
=> Added exceptions for broken links checker

dependencies.md, doc/changes/changes_2.9.8.md, maven-project-crawler/pk_generated_parent.pom, parent-pom/pom.xml, pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileGenerator.java, project-keeper/src/main/resources/maven_templates/duplicate-finder-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/error-code-crawler-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/flatten-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/jacoco-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-assembly-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-dependency-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-failsafe-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-gpg-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-source-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-surefire-plugin.xml, project-keeper/src/main/resources/maven_templates/versions-maven-plugin.xml, shared-model-classes/pk_generated_parent.pom, shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/dependencychanges/DependencyChange.java, shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/dependencychanges/DependencyChangeReport.java, shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/mavenprojectcrawler/MavenProjectCrawlResult.java, shared-model-classes/src/test/java/com/exasol/projectkeeper/shared/MavenProjectCrawlResultTest.java, shared-test-setup/pk_generated_parent.pom
=> #449: Migrate to latest yasson version

doc/changes/changelog.md, doc/changes/changes_2.9.9.md, error_code_config.yml, maven-project-crawler/pk_generated_parent.pom, parent-pom/pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/plugin/ErrorCodeCrawlerPluginTemplateGenerator.java, project-keeper/src/main/resources/maven_templates/error-code-crawler-maven-plugin.xml, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom
=> #456: Upgrade error code crawler

.github/workflows/ci-build.yml, doc/changes/changes_2.9.10.md, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml
=> #467: Run sonar with Java 17

.github/workflows/ci-build.yml, .github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_2.9.11.md, maven-project-crawler/pk_generated_parent.pom, maven-project-crawler/pom.xml, parent-pom/pom.xml, pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-cli/pom.xml, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper-maven-plugin/pom.xml, project-keeper/pk_generated_parent.pom, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileGenerator.java, project-keeper/src/main/resources/maven_templates/maven-enforcer-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-source-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-surefire-plugin.xml, project-keeper/src/main/resources/non_maven_templates/.github/workflows/project-keeper-verify.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build-native-build.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml, project-keeper/src/main/resources/templates/.github/workflows/release_droid_prepare_original_checksum.yml, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom
=> #470: Three small improvements

README.md, doc/changes/changelog.md, doc/changes/changes_2.9.15.md, doc/developers_guide/developers_guide.md, parent-pom/pom.xml
=> #485: Added note about `--projects .` command line option to user guide

dependencies.md, doc/changes/changelog.md, doc/changes/changes_2.9.16.md, maven-project-crawler/pk_generated_parent.pom, maven-project-crawler/pom.xml, parent-pom/pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper-maven-plugin/pom.xml, project-keeper/pk_generated_parent.pom, project-keeper/src/main/resources/maven_templates/maven-compiler-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-dependency-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-failsafe-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-javadoc-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-surefire-plugin.xml, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom
=> #497: Enabled linter warnings

doc/changes/changes_2.9.17.md, project-keeper/src/main/resources/templates/.github/workflows/ci-build-db-version-matrix.yml
=> #504: Use single job name for Matrix builds

.vscode/settings.json, dependencies.md, doc/changes/changes_4.0.0.md, maven-project-crawler/pk_generated_parent.pom, parent-pom/error_code_config.yml, parent-pom/pom.xml, pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-cli/pom.xml, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper-maven-plugin/pom.xml, project-keeper/pk_generated_parent.pom, project-keeper/pom.xml, project-keeper/src/main/resources/maven_templates/versions-maven-plugin.xml, shared-model-classes/pk_generated_parent.pom, shared-model-classes/pom.xml, shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/mavenprojectcrawler/MavenProjectCrawlResult.java, shared-model-classes/src/test/java/com/exasol/projectkeeper/shared/repository/GitRepositoryTest.java, shared-test-setup/pk_generated_parent.pom, shared-test-setup/pom.xml
=> #515: Upgrade dependencies

project-keeper-maven-plugin/src/test/java/com/exasol/projectkeeper/plugin/MvnProjectWithProjectKeeperPluginWriter.java, project-keeper/src/main/java/com/exasol/projectkeeper/JavaProjectCrawlerRunner.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/MavenSourceAnalyzer.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/generic/CommandExecutor.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/generic/MavenProcessBuilder.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/generic/ProcessResult.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/generic/ShellCommand.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/generic/SimpleProcess.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoBinary.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangServices.java, project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/npm/NpmServices.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFile.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileIO.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/io/PomFileReader.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/io/PomFileWriter.java, project-keeper/src/test/java/com/exasol/projectkeeper/JavaProjectCrawlerRunnerIT.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/generic/ProcessResultTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GoBinaryTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/npm/NpmServicesTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileIOTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java
=> Refactor command executor & POM reading/writing

doc/changes/changes_4.2.1.md, doc/requirements/design.md, project-keeper/src/main/java/com/exasol/projectkeeper/github/GitHubWorkflowOutput.java, project-keeper/src/test/java/com/exasol/projectkeeper/github/GitHubWorkflowOutputTest.java
=> Prefixed release letter on GitHub with version number

.github/workflows/ci-build.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, doc/changes/changes_4.2.1.md, project-keeper/src/main/java/com/exasol/projectkeeper/validators/VersionIncrementValidator.java, project-keeper/src/main/resources/non_maven_templates/.github/workflows/project-keeper-verify.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml, project-keeper/src/test/java/com/exasol/projectkeeper/validators/VersionIncrementValidatorTest.java
=> #545 Allow "v" prefix for version numbers

.github/workflows/ci-build.yml, .github/workflows/release.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, doc/changes/changes_4.2.1.md, doc/requirements/design.md, pom.xml, project-keeper/src/main/resources/templates/.github/workflows/ci-build-db-version-matrix.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml, project-keeper/src/main/resources/templates/.github/workflows/dependencies_update.yml, project-keeper/src/main/resources/templates/.github/workflows/release.yml
=> #548: Skip release when preconditions are not fulilled

doc/changes/changelog.md, doc/changes/changes_4.3.1.md, parent-pom/pom.xml
=> #570: Fixed CVE-2024-31573

.github/workflows/dependencies_update.yml, doc/changes/changelog.md, doc/changes/changes_4.3.3.md, parent-pom/pom.xml, project-keeper/src/main/resources/templates/.github/workflows/dependencies_update.yml
=> #580: Fix shell script in automatic dependency update workflow

doc/changes/changes_4.3.4.md, maven-project-crawler/pk_generated_parent.pom, maven-project-crawler/pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-cli/pom.xml, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper-maven-plugin/pom.xml, project-keeper/pk_generated_parent.pom, project-keeper/pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileGenerator.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileGeneratorTest.java, shared-model-classes/pk_generated_parent.pom, shared-model-classes/pom.xml, shared-test-setup/pk_generated_parent.pom, shared-test-setup/pom.xml
=> #530: Use `java.version` property from parent pom if available

dependencies.md, doc/changes/changelog.md, doc/changes/changes_4.4.1.md, maven-project-crawler/pk_generated_parent.pom, parent-pom/pom.xml, pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/CiBuildWorkflowGenerator.java, project-keeper/src/main/resources/maven_templates/maven-dependency-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-deploy-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-failsafe-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-javadoc-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-site-plugin.xml, project-keeper/src/main/resources/maven_templates/maven-surefire-plugin.xml, project-keeper/src/main/resources/maven_templates/sonar-maven-plugin.xml, project-keeper/src/main/resources/maven_templates/versions-maven-plugin.xml, project-keeper/src/test/java/com/exasol/projectkeeper/validators/files/CiBuildWorkflowGeneratorTest.java, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom
=> #602: Fixed customization of java version

doc/changes/changes_5.0.0.md, maven-project-crawler/.settings/org.eclipse.jdt.core.prefs, project-keeper-cli/.settings/org.eclipse.jdt.core.prefs, project-keeper-maven-plugin/.settings/org.eclipse.jdt.core.prefs, project-keeper/.settings/org.eclipse.jdt.core.prefs, project-keeper/src/main/resources/templates/.settings/org.eclipse.jdt.core.prefs, shared-model-classes/.settings/org.eclipse.jdt.core.prefs, shared-test-setup/.settings/org.eclipse.jdt.core.prefs
=> #609: Update Eclipse formatter configuration to never join wrapped lines

.github/workflows/ci-build.yml, .github/workflows/test_linux_build_on_windows.yml, .github/workflows/test_on_windows.yml, doc/changes/changes_5.0.0.md, doc/user_guide/user_guide.md, project-keeper/src/main/resources/non_maven_templates/.github/workflows/project-keeper-verify.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build-db-version-matrix.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build-native-build.yml, project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml
=> #620: Run CI build when a PR is marked as ready for review

doc/changes/changes_5.0.0.md, maven-project-crawler/pk_generated_parent.pom, parent-pom/pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/src/main/resources/maven_templates/versions-maven-plugin.xml, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom
=> #619: Move `versions-maven-plugin` to verify phase

doc/changes/changes_5.0.0.md, parent-pom/pom.xml, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflow.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowEnvironmentCustomizer.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowStepCustomizer.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowEnvironmentCustomizerTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowTest.java
=> 614: Improve error message for unknown job ID in workflow customization

project-keeper-cli/src/test/java/com/exasol/projectkeeper/cli/ProjectKeeperLauncherIT.java, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/BaseProjectFixture.java, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/FixtureHelpers.java, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/GolangProjectFixture.java, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/MavenProjectFixture.java, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/NpmProjectFixture.java
=>  #615: Add integration test with NPM

doc/changes/changes_5.0.0.md, doc/user_guide/user_guide.md, shared-test-setup/src/main/java/com/exasol/projectkeeper/test/NpmProjectFixture.java
Closes #610
Also fixes review finding https://github.com/exasol/project-keeper/pull/627#discussion_r1989451142
=> #610: Document `job` field for workflow customizations

doc/requirements/design.md, doc/user_guide/user_guide.md, project-keeper/error_code_config.yml, project-keeper/src/main/java/com/exasol/projectkeeper/config/ProjectKeeperConfigReader.java, project-keeper/src/main/java/com/exasol/projectkeeper/config/ProjectKeeperRawConfig.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/CiBuildWorkflowGenerator.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflow.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowCustomizer.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowEnvironmentCustomizer.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowJavaVersionCustomizer.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowJobPermissionsCustomizer.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowStepCustomizer.java, project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/WorkflowCustomizer.java, project-keeper/src/test/java/com/exasol/projectkeeper/config/ProjectKeeperConfigReaderTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/files/CiBuildWorkflowGeneratorTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowCustomizerTest.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowEnvironmentCustomizerTest.java, shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/config/workflow/CustomJob.java, shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/config/workflow/CustomWorkflow.java, shared-model-classes/src/main/java/com/exasol/projectkeeper/shared/config/workflow/JobPermissions.java, shared-model-classes/src/test/java/com/exasol/projectkeeper/shared/config/workflow/CustomJobTest.java, shared-model-classes/src/test/java/com/exasol/projectkeeper/shared/config/workflow/JobPermissionsTest.java
=> #611: Customize job permissions

doc/changes/changes_5.0.0.md, maven-project-crawler/pk_generated_parent.pom, parent-pom/pom.xml, project-keeper-cli/pk_generated_parent.pom, project-keeper-maven-plugin/pk_generated_parent.pom, project-keeper/pk_generated_parent.pom, project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileGenerator.java, project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileGeneratorTest.java, shared-model-classes/pk_generated_parent.pom, shared-test-setup/pk_generated_parent.pom
=> #613: Allow excluding tests via JUnit tags

.github/workflows/dependencies_check.yml, doc/changes/changes_5.1.0.md, project-keeper/src/main/resources/templates/.github/workflows/dependencies_check.yml
=> #641: Pin python-toolbox version
